version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/precomputed:/app/backend/precomputed
      - ./submission.csv:/app/submission.csv
      - ./"[PUB] India_runs_data_and_ai_challenge"/India_runs_data_and_ai_challenge:/app/"[PUB] India_runs_data_and_ai_challenge"/India_runs_data_and_ai_challenge
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
